version: '3.8'

services:
  master:
    image: citusdata/citus:10.1
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    ports:
      - "5432:5432"
    networks:
      - citus_network
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - master_data:/var/lib/postgresql/data

  worker1:
    image: citusdata/citus:10.1
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    networks:
      - citus_network
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - worker1_data:/var/lib/postgresql/data

  worker2:
    image: citusdata/citus:10.1
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    networks:
      - citus_network
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - worker2_data:/var/lib/postgresql/data

  coordinator:
    image: citusdata/citus:10.1
    environment:
      POSTGRES_USER: citus
      POSTGRES_PASSWORD: citus
      POSTGRES_DB: citus
    ports:
      - "5432:5432"
    networks:
      - citus_network
    depends_on:
      - worker1
      - worker2
    command: >
      bash -c "until pg_isready -h master; do sleep 1; done;
               until pg_isready -h worker1; do sleep 1; done;
               until pg_isready -h worker2; do sleep 1; done;
               psql -h master -U citus -d citus -c \"SELECT * from master_add_node('worker1', 5432);\"
               psql -h master -U citus -d citus -c \"SELECT * from master_add_node('worker2', 5432);\""

networks:
  citus_network:
    driver: bridge

volumes:
  master_data:
  worker1_data:
  worker2_data:
