version: "3.8"

services:
  master-one:
    image: "citusdata/citus:12.1.3"
    ports: ["5432:5432"]
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH1
      CITUS_HOST: "master"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGUSER: "pguser"
      PGPASSWORD: "pgpasswd"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    networks:
      - cluster
      - default

  manager:
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-one:/healthcheck
    depends_on: [master]
    environment: *AUTH1
    networks:
      - default

  worker-1:
    image: "citusdata/citus:12.1.3"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH1
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-one:/healthcheck
    networks:
      - default

  worker-2:
    image: "citusdata/citus:12.1.3"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH1
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-one:/healthcheck
    networks:
      - default
    
volumes:
  healthcheck-one:

networks:
  default:
      driver: bridge
  cluster:
    name: citusclusters